name:                tortues
version:             0.1.0
author:              barsanges
maintainer:          https://github.com/barsanges
copyright:           2025 barsanges

extra-source-files:
- README.md

synopsis:            A solver for the game "Le lièvre et les tortues"
description:         Please see the README

dependencies:
- aeson
- base
- bytestring
- containers
- search-algorithms
- vector

library:
  source-dirs: src

executables:
  tortues:
    source-dirs:     app
    main:            Main.hs
    dependencies:
    - combinatorial
    - optparse-applicative
    - tortues

tests:
  tortues-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - hspec
    - tortues