name: ci

on: [push, pull_request]

jobs:
  stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: haskell-actions/setup@v2
        name: Setup Haskell Stack
        with:
          enable-stack: true

      - uses: actions/cache@v4
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack

      - name: Build
        run: stack build

      - name: Test
        run: stack test